---
Name: markdown
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripers\markdown\extensions\MarkdownFieldExtension
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripers\markdown\extensions\MarkdownDataObjectExtension
